### ISSUE TITLE
haven-wallet-rpc

### ISSUE THREAD

**Issue by DLI-PLATFORM** [haven-protocol-org/haven-offshore#15]
We have scripts that access several monero based wallet rpcs. This update has changed the way it works and has broken the scripts,. It appears to be because of asset_type. Could the asset type be set to XHV by default without having to specify it? This would allow the wallet-rpc to conform to previous standards.

Here is the output: Request have return error: Paremeter 'asset_type' is not supported. Currently supported asset types are: XHV, XAG, XAU, XAUD, XBTC, XCAD, XCHF, XCNY, XEUR, XGBP, XJPY, XNOK, XNZD, XUSD

Thank you!

**Comment by neilcoggins** [comment]
I assume that the RPC calls in question are `get_balance` and similar?

The issue is that lots of people are using buggy scripts to access these RPC methods, and those scripts do not conform to the "standards" as laid down in the documentation for either [Monero](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#get_balance) or [Haven](https://docs.havenprotocol.org/rpc/1.3.0a/RPC_API.html#get_balance). As documented by Monero as well as ourselves, the RPC call is expected to provide a `params` object because the `account_index` parameter is **not** optional. We actually allow an empty `params` object, which is not technically permitted but works with Monero as well. By way of example, 

`curl http://127.0.0.1:17752/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_balance","params":{}}' -H 'Content-Type: application/json'` 

works as you want for both Monero and Haven, whereas

`curl http://127.0.0.1:17752/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_balance"}' -H 'Content-Type: application/json'` 

is not valid for either, and doesn't work for Haven (but does for Monero). If you add an empty `params` object to your call, the scripts will succeed for all Monero forks including Haven, and there will be no need to specify `asset_type` for XHV balances.
